Repository LunatiqueCoder/react-native-media-console, pull requests merged in 2023-01, with the labels that each got.

#43 Add Overlay component
  src/VideoPlayer.tsx
  src/components/Overlay.tsx
  src/components/index.ts
Labels: bug, good first issue

#42 Add prop showOnEnd
  README.md
  src/VideoPlayer.tsx
  src/types.ts
Labels: enhancement, good first issue

#46 add "disableSeekButtons" property for hiding rewind/fast forward
  README.md
  src/VideoPlayer.tsx
  src/components/PlayPause/PlayPause.tsx
  src/types.ts
Labels: enhancement
